pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - apt-get update
      - apt-get install -y rsync

      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-rsync
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

services:
  rsync:
    image: msteinert/drone-rsync-test
    pull: true

plugin:
  name: Rsync
  desc: Deploy or update a project via Rsync
  type: deploy
  image: plugins/drone-rsync
  labels:
    - deploy
    - ssh
    - rsync
