build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - apt-get update && apt-get install -y rsync

    - make deps
    - make vet
    - make build
    - make test

compose:
  rsync:
    image: msteinert/drone-rsync-test
    pull: true

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-rsync
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-rsync
    tag: develop
    when:
      branch: develop

plugin:
  name: Rsync
  desc: Deploy or update a project via Rsync
  type: deploy
  image: plugins/drone-rsync
  labels:
    - deploy
    - ssh
    - rsync
