build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - apt-get update && apt-get install -y rsync
    - go get
    - go build
    - go test

compose:
  rsync:
    image: msteinert/drone-rsync-test
    pull: true

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-rsync
    when:
      branch: master

plugin:
  name: Rsync
  desc: Uses rsync to upload files to a remote server
  type: deploy
  image: plugins/drone-rsync
  labels:
    - deploy
    - ssh
    - rsync
